# Generated by Django 4.1 on 2023-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleprocessing', '0002_operator_delete_operatorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='password',
            new_name='op_pw',
        ),
    ]
