# Generated by Django 4.1 on 2023-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleprocessing', '0004_shipinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipinfo',
            name='sog',
            field=models.FloatField(max_length=100),
        ),
    ]
