# Generated by Django 4.1 on 2023-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleprocessing', '0005_alter_shipinfo_sog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('etc', models.CharField(max_length=100)),
            ],
        ),
    ]
