# Generated by Django 4.1 on 2023-05-27 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleprocessing', '0006_dangermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangermessages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 16, 38, 19, 344585), max_length=100),
        ),
    ]
